'use client';
import React from 'react';
import {Box,Container,Heading,Text,Button,Flex,VStack,HStack,Badge,SimpleGrid,Icon,List,ListItem,ListIcon} from '@chakra-ui/react';
import {Helmet} from 'react-helmet-async';
import {Link} from 'react-router-dom';
import {MdCheckCircle,MdLocationOn,MdEvent} from 'react-icons/md';
const ConvergenceIndia2026=()=>{
const es={"@context":"https://schema.org","@type":"Event","name":"VMukti at Convergence India 2026","description":"Visit VMukti at Convergence India 2026 for AI video surveillance demos.","startDate":"2026-03-23T10:00+05:30","endDate":"2026-03-25T18:00+05:30","eventStatus":"https://schema.org/EventScheduled","eventAttendanceMode":"https://schema.org/OfflineEventAttendanceMode","location":{"@type":"Place","name":"Bharat Mandapam","address":{"@type":"PostalAddress","streetAddress":"Pragati Maidan","addressLocality":"New Delhi","postalCode":"110001","addressCountry":"IN"}},"performer":{"@type":"Organization","name":"VMukti Solutions","url":"https://www.vmukti.com"}};
const bc={"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://www.vmukti.com/"},{"@type":"ListItem","position":2,"name":"Events","item":"https://www.vmukti.com/whoweare/eventspotlight"},{"@type":"ListItem","position":3,"name":"Convergence India 2026"}]};
const demos=[{title:"AI-Powered Cloud VMS",desc:"Live demo of cloud-native video management with AI analytics and ANPR."},{title:"Edge AI Cameras",desc:"Real-time edge processing with on-camera AI for intrusion and fire detection."},{title:"Smart City Command Center",desc:"Integrated ICCC solution for urban surveillance and emergency response."},{title:"ArcisAI Platform",desc:"Next-gen AI surveillance with generative AI search and predictive analytics."}];
return(<Box bg="#E7E7E7" minH="100vh"><Helmet><title>VMukti at Convergence India 2026 | Booth F4-06, Hall 04</title>
<meta name="description" content="Visit VMukti at Convergence India 2026, March 23-25, Bharat Mandapam, New Delhi. Booth F4-06, Hall 04. AI cloud VMS, edge AI, smart city solutions." />
<meta name="keywords" content="Convergence India 2026,VMukti,AI surveillance,cloud VMS,edge AI,smart city,CCTV,Bharat Mandapam" />
<link rel="canonical" href="https://www.vmukti.com/events/convergence-india-2026" />
<meta property="og:title" content="VMukti at Convergence India 2026" />
<meta property="og:description" content="AI surveillance demos at Booth F4-06, Hall 04, Bharat Mandapam." />
<meta property="og:type" content="event" />
<script type="application/ld+json">{JSON.stringify(es)}</script>
<script type="application/ld+json">{JSON.stringify(bc)}</script>
</Helmet>
<Box bg="linear-gradient(135deg,#1a1a2e 0%,#0f3460 100%)" color="white" py={{base:12,md:20}} px={4}><Container maxW="1200px"><Flex direction={{base:"column",md:"row"}} align="center" gap={8}><VStack align={{base:"center",md:"flex-start"}} spacing={4} flex={1}><Badge colorScheme="orange" fontSize="md" px={3} py={1}>March 23-25, 2026</Badge><Heading as="h1" size={{base:"xl",md:"2xl"}}>VMukti at Convergence India 2026</Heading><Text fontSize={{base:"md",md:"lg"}} opacity={0.9}>Experience AI-powered video surveillance. Visit us at <strong>Booth F4-06, Hall 04</strong>, Bharat Mandapam, New Delhi.</Text><HStack spacing={4} pt={2}><Button as={Link} to="/book-a-demo" colorScheme="orange" size="lg">Book a Meeting</Button><Button as={Link} to="/solution" variant="outline" colorScheme="whiteAlpha" size="lg">Explore Solutions</Button></HStack></VStack>
<Box flex={1} textAlign="center"><Box bg="whiteAlpha.100" borderRadius="xl" p={6} border="1px solid" borderColor="whiteAlpha.200"><VStack spacing={3}><Icon as={MdLocationOn} boxSize={8} color="orange.300"/><Text fontWeight="bold" fontSize="lg">Booth F4-06, Hall 04</Text><Text>Bharat Mandapam, New Delhi</Text><Badge colorScheme="green" fontSize="sm">Free Entry for Trade Visitors</Badge></VStack></Box></Box></Flex></Container></Box>
<Box py={{base:10,md:16}} px={4}><Container maxW="1200px"><VStack spacing={8}><Heading as="h2" size="xl" textAlign="center">What We Are Showcasing</Heading><SimpleGrid columns={{base:1,md:2}} spacing={6} w="100%">{demos.map((d,i)=>(<Box key={i} bg="white" p={6} borderRadius="lg" boxShadow="md"><Heading as="h3" size="md" mb={3} color="#0f3460">{d.title}</Heading><Text color="gray.600">{d.desc}</Text></Box>))}</SimpleGrid></VStack></Container></Box>
<Box bg="white" py={{base:10,md:16}} px={4}><Container maxW="1200px"><Flex direction={{base:"column",md:"row"}} gap={8} align="center"><VStack align="flex-start" spacing={4} flex={1}><Heading as="h2" size="xl">Why Visit VMukti?</Heading><List spacing={3}><ListItem><ListIcon as={MdCheckCircle} color="green.500"/>Live AI surveillance demos with real-time analytics</ListItem><ListItem><ListIcon as={MdCheckCircle} color="green.500"/>One-on-one consultation with AI experts</ListItem><ListItem><ListIcon as={MdCheckCircle} color="green.500"/>Exclusive event pricing on cloud VMS</ListItem><ListItem><ListIcon as={MdCheckCircle} color="green.500"/>Partnership and reseller opportunities</ListItem><ListItem><ListIcon as={MdCheckCircle} color="green.500"/>See ArcisAI next-gen platform in action</ListItem></List></VStack>
<Box flex={1}><Box bg="#f8f9fa" borderRadius="xl" p={8}><VStack spacing={4}><Icon as={MdEvent} boxSize={10} color="orange.400"/><Heading as="h3" size="md">Event Details</Heading><Text><strong>Date:</strong> March 23-25, 2026</Text><Text><strong>Venue:</strong> Bharat Mandapam, New Delhi</Text><Text><strong>Booth:</strong> F4-06, Hall 04</Text><Button as={Link} to="/contact-us" colorScheme="blue" size="md" mt={2}>Schedule a Visit</Button></VStack></Box></Box></Flex></Container></Box>
<Box bg="linear-gradient(135deg,#0f3460 0%,#1a1a2e 100%)" color="white" py={12} px={4} textAlign="center"><Container maxW="800px"><Heading as="h2" size="lg" mb={4}>Ready to Experience the Future of Surveillance?</Heading><Text mb={6} opacity={0.9}>Book a meeting with our team at Convergence India 2026.</Text><HStack justify="center" spacing={4}><Button as={Link} to="/book-a-demo" colorScheme="orange" size="lg">Book a Demo</Button><Button as={Link} to="/contact-us" variant="outline" colorScheme="whiteAlpha" size="lg">Contact Us</Button></HStack></Container></Box></Box>);};
export default ConvergenceIndia2026;